# RAG Multimodal Application Configuration

# Model Configuration
model:
  # LLM chat model, model chính, tạo phản hồi, chấm điểm, gọi tools 
  text_generation: "qwen3:1.7b"
  # Embedding model 
  embeddings: "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
  # Embedding tokenizer
  tokenizer: "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
  # Base URL trỏ tới Ollama OpenAI-compatible API
  url: "http://localhost:11434/v1"
  timeout: 60
  # Model để tạo picture description
  vision_model: "granite3.2-vision:latest"

# Docling Document Processing
document:
  image_resolution_scale: 2  # Scale factor for image resolution in document processing
  max_tokens: 512  # Maximum number of tokens for chunking
  doc_dir: "doc_sources"  # Directory containing document sources
  supported_file_types: [".pdf"]  # List of supported file extensions
  picture_description:
    # Bật/tắt chức năng picture description. Khi false, pipeline sẽ không gọi remote API
    enabled: true
    prompt_picture_description: "Miêu tả chi tiết hình ảnh sau bằng một đoạn văn."

# Vector Database Configuration
database:
  uri: "http://localhost:19530"  # Milvus database URI
  name: "gil"  # Database name
  collection_name: "multimodal_rag"  # Collection name
  # namespace: "viettel"  # Namespace for partitioning data

# Retrieval Configuration
retrieval:
  k: 3  # Number of documents to retrieve
  weights: [0.7, 0.3]  # Weights for hybrid search (dense, sparse)